version: '3.8'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:11
    container_name: postgres
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local